package finalfantasy.api.enums;

import javax.persistence.*;

public enum GameDescription {

    FF_1_DESCRIPTION("Final Fantasy takes place in a fantasy medieval setting with three major continents, and the four Warriors of Light begin in Cornelia. They are tasked by the King of Cornelia to rescue Princess Sarah from Garland, and after defeating him, the king opens up a bridge enabling them to pass to the town of Pravoka. This sets them off on an adventure to defeat the Four Fiends and rescue the world."),
    FF_2_DESCRIPTION("The game centers on a conflict by the Palamecian Empire, whose Emperor Mateus is using hellspawn to try to conquer the world. The protagonist, Firion, along with his allies Maria and Guy, join the Wild Rose Rebellion to fight them, and meet many allies along the way to try to stop the Emperor and save the world."),
    FF_3_DESCRIPTION("The story revolves around four Warriors of Light who begin as Onion Knights in the original release, although they are named Luneth, Arc, Refia and Ingus in the 3D remake. When they find the Wind Crystal, it grants them its power, and instructs them to restore balance to the world."),
    FF_4_DESCRIPTION("The game takes place in a medieval fantasy setting, and focuses on Cecil Harvey, the captain of the Red Wings of Baron. After performing a raid on Mysidia to steal the Water Crystal, Cecil and the knights question the orders of their king as they believed stealing from the Mysidians was wrong. As punishment for disloyalty, the king strips Cecil of his title, and orders him and Kain Highwind to win back his trust by sending him to the village of Mist. This sets Cecil off on an adventure in which he and many other allies he meets must uncover the truth and save the world from monsters."),
    FF_5_DESCRIPTION("The game takes place in a medieval fantasy setting, and centers on a group of four strangers brought together by circumstance to save the Crystals that have mysteriously begun shattering. The one behind the phenomenon is the antagonist Exdeath, as part of a plan to release himself from imprisonment and gain the power of the Void, a realm of nothingness, which could bestow absolute power on one able to resist being absorbed by it. The four become the Warriors of Light and turn their attentions to defeating Exdeath and stopping the Void's energies from consuming their world."),
    FF_6_DESCRIPTION("Final Fantasy VI focuses on a conflict between the Gestahlian Empire conquering the world and a rebel faction opposed to them known as the Returners, taking place in a fantasy steampunk-style world. The Empire has acquired great power by experimenting on captured espers, magical creatures of legend. The Returners seek magical power to fight the Empire on equal terms, and an amnesiac former imperial soldier, Terra Branford, proves key to both sides for understanding magic and espers."),
    FF_7_DESCRIPTION("Final Fantasy VII follows the story of mercenary Cloud Strife, who is hired by the eco-terrorist group AVALANCHE—led by Barret Wallace—to help fight the mega-corporation Shinra Electric Power Company, who attempts to drain the planet's lifeblood as an energy source to further their profits. Apathetic to the cause, Cloud initially fights for personal gain, and for the promise he made to childhood friend Tifa Lockhart. Cloud eventually joins forces with many others to save the planet, which is threatened by Shinra and Cloud's nemesis Sephiroth, and discovers a reason to fight for a cause other than his own."),
    FF_8_DESCRIPTION ("The story of Final Fantasy VIII follows Squall Leonhart, a cadet in a military academy called Balamb Garden. Squall strives to become a SeeD, a mercenary who can wield magic with the aid of magical beings known as Guardian Forces. Balamb Garden is the only institution in the world to allow the use of the beings, and their use mimics the power of a sorceress, women who can use magic naturally who are both feared and revered. Though initially a loner, Squall's quest has him befriend various people and he learns to depend on them as the SeeDs get involved in a mission of protecting the world."),
    FF_9_DESCRIPTION("Taking place on planet Gaia, the story follows a thief named Zidane Tribal, a member of a thief troupe who is tasked to kidnap the princess of Alexandria, Garnet Til Alexandros XVII. He teams up with her and a team of allies to stop Queen Brahne and her ally Kuja from waging war with an army of black mages."),
    FF_10_DESCRIPTION("The game is set in the world of Spira and follows the story of Tidus and Yuna. Tidus is a star athlete blitzball player, who is taken to Spira by Auron after a monster called Sin destroys his home city of Zanarkand. Tidus then joins the summoner, Yuna on her pilgrimage with her guardians to defeat Sin and bring about the Calm."),
    FF_10_2DESCRIPTION("The game takes place in Spira during the Eternal Calm, two years after Final Fantasy X. It continues the story of Yuna, who has become a sphere hunter and a member of the sphere hunting group, the Gullwings, with Rikku and Paine. Yuna hunts for spheres to find clues about a mysterious man who looks like her lost love Tidus. However, she becomes entangled in political turmoil the Gullwings must resolve to prevent a war, uncovering a plot to destroy Spira with a secret weapon from its ancient past."),
    FF_12_DESCRIPTION("The game is set in the continent of Ivalice, in which the Archadian and Rozarrian Empires wage an endless war for power, and Dalmasca has been caught between the two and annexed by Archadia. Dalmasca's princess, Ashelia B'nargin Dalmasca, has created a resistance movement against Archadia to avenge her fallen kingdom, and along the way is united with a band of allies to seek a power capable of defeating the Archadian Empire."),
    FF_13_DESCRIPTION("Final Fantasy XIII is set on the world of Gran Pulse, above which floats Cocoon, an artificial biodome on which humanity lives, fearful of the surface world. Lightning, a member of the Guardian Corps military forces, goes rogue when her sister Serah is branded a l'Cie by a fal'Cie from Gran Pulse, designating her an enemy of Cocoon. The Sanctum government authorizes a Purge of citizens who may have come in contact with the fal'Cie, and Lightning meets up with the pilot Sazh Katzroy on her way to find Serah amid the Purge. Also caught up in the Purge are Snow Villiers, Serah's fiance and leader of the anti-authority group, NORA, and the civilians Hope Estheim and Oerba Dia Vanille. The five come into contact with the Pulse fal'Cie, Anima, and are branded l'Cie, seemingly with the Focus to destroy Cocoon."),
    FF_15_DESCRIPTION("The story is told over the course of 15 chapters. It focuses on Noctis Lucis Caelum, a prince from the kingdom of Lucis who fights to reclaim his throne and must go on to fulfill a greater destiny. Final Fantasy XV aims to examine its characters' humanity and place them in a more realistic setting than most Final Fantasy games. Its prominent themes are friendship, destiny, and legacy."),
    FF_TACTICTS("The game is set in Ivalice, a unified kingdom of seven territories, which is caught in the middle of the War of the Lions fought between two opposing factions vying for rule of the kingdom. The story focuses on Ramza Beoulve, a member of the respected House Beoulve, who finds himself caught amid the war and later uncovers the truth behind a sinister plot behind it."),
    FF_DISSIDIA("Dissidia Final Fantasy is a sub-franchise of fighting games in the Final Fantasy series. It is a crossover containing characters and locations from other games in the series, and having them fight against one another in a battle between two gods, originally between Cosmos and Chaos, and later between Spiritus and Materia.");

    GameDescription(String description) {
    }
}